<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ strtoupper($key->algorithm) }} Key #{{ $key->id }} &mdash; {{ $key->purpose }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-3xl mx-auto sm:px-6 lg:px-8 space-y-6">

            @if (session('status'))
                <div class="p-4 bg-green-100 border border-green-300 text-green-800 rounded">
                    {{ session('status') }}
                </div>
            @endif

            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-6">
                <dl class="grid grid-cols-2 gap-4 text-sm">
                    <div><dt class="text-gray-500">Algorithm</dt><dd class="font-semibold uppercase">{{ $key->algorithm }}</dd></div>
                    <div><dt class="text-gray-500">Purpose</dt><dd class="font-semibold">{{ $key->purpose }}</dd></div>
                    <div><dt class="text-gray-500">Key size</dt><dd>{{ $key->key_size ? $key->key_size . ' bits' : 'secp256k1 (256-bit curve)' }}</dd></div>
                    <div><dt class="text-gray-500">Version</dt><dd>v{{ $key->version }}</dd></div>
                    <div>
                        <dt class="text-gray-500">Status</dt>
                        <dd>
                            @php
                                $badge = [
                                    'active' => 'bg-green-100 text-green-800',
                                    'rotated' => 'bg-yellow-100 text-yellow-800',
                                    'revoked' => 'bg-red-100 text-red-800',
                                ][$key->status] ?? 'bg-gray-100 text-gray-800';
                            @endphp
                            <span class="px-2 py-1 rounded text-xs font-semibold {{ $badge }}">{{ ucfirst($key->status) }}</span>
                        </dd>
                    </div>
                    <div><dt class="text-gray-500">Created</dt><dd>{{ $key->created_at->format('Y-m-d H:i') }}</dd></div>
                    @if ($key->rotated_at)
                        <div><dt class="text-gray-500">Rotated at</dt><dd>{{ $key->rotated_at->format('Y-m-d H:i') }}</dd></div>
                    @endif
                    @if ($key->rotatedFrom)
                        <div>
                            <dt class="text-gray-500">Rotated from</dt>
                            <dd><a class="text-indigo-600 hover:underline" href="{{ route('admin.keys.show', $key->rotatedFrom) }}">Key #{{ $key->rotatedFrom->id }}</a></dd>
                        </div>
                    @endif
                    @if ($key->generatedBy)
                        <div><dt class="text-gray-500">Generated by</dt><dd>{{ $key->generatedBy->name }}</dd></div>
                    @endif
                </dl>

                <div class="mt-6">
                    <x-input-label value="Fingerprint (SHA-256 of public key)" />
                    <code class="block mt-1 p-2 bg-gray-50 border rounded text-xs break-all">{{ $key->fingerprint }}</code>
                </div>

                <div class="mt-6">
                    <x-input-label value="Public Key" />
                    <textarea readonly rows="4" onclick="this.select()"
                              class="mt-1 block w-full font-mono text-xs bg-gray-50 border-gray-300 rounded-md">{{ $key->public_key }}</textarea>
                    <p class="text-xs text-gray-500 mt-1">Safe to share. The private key is never displayed in this interface.</p>
                </div>
            </div>

            <div class="flex items-center gap-3">
                <a href="{{ route('admin.keys.export', $key) }}"
                   class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700">
                    Export Public Key
                </a>

                @if ($key->status === 'active')
                    <form method="POST" action="{{ route('admin.keys.rotate', $key) }}"
                          onsubmit="return confirm('Rotate this key? The old key stays readable (status: rotated) so existing encrypted data remains decryptable.');">
                        @csrf
                        <x-primary-button>Rotate Key</x-primary-button>
                    </form>

                    <form method="POST" action="{{ route('admin.keys.revoke', $key) }}"
                          onsubmit="return confirm('Revoke this key? Data still encrypted under it will become unreadable. This cannot be undone.');">
                        @csrf
                        <x-danger-button>Revoke</x-danger-button>
                    </form>
                @endif

                <a href="{{ route('admin.keys.index') }}" class="text-sm text-gray-600 hover:underline ml-auto">Back to all keys</a>
            </div>
        </div>
    </div>
</x-app-layout>
